n1 <- readline(prompt=" Enter first fractional Input: ")
n2 <- readline(prompt=" Enter second fractional Input: ")
n1 <- as.double(n1)
n2 <- as.double(n2)
cat("Difference of two fractional Input is: ",n1-n2)
